# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Basis <- function(t, knM) {
    .Call('bmsaplm_Basis', PACKAGE = 'bmsaplm', t, knM)
}

#' @export
CentMat <- function(X, meanX) {
    .Call('bmsaplm_CentMat', PACKAGE = 'bmsaplm', X, meanX)
}

#' Generate a basis matrix
#'
#' @param X matrix.
#' @param knM lisy.
#' @examples
#' CombBasis(cbind(1:10,16:25),list(c(2,5,8),c(18,20,22)))
NULL

#' @export
CombBasis <- function(X, knM) {
    .Call('bmsaplm_CombBasis', PACKAGE = 'bmsaplm', X, knM)
}

DeltaPrior <- function(listdelta, gamma, mu, var, numkn, mu0, phat, p) {
    .Call('bmsaplm_DeltaPrior', PACKAGE = 'bmsaplm', listdelta, gamma, mu, var, numkn, mu0, phat, p)
}

Eta <- function(delta, gamma, p, q) {
    .Call('bmsaplm_Eta', PACKAGE = 'bmsaplm', delta, gamma, p, q)
}

GammaPrior <- function(gamma, p, q) {
    .Call('bmsaplm_GammaPrior', PACKAGE = 'bmsaplm', gamma, p, q)
}

LogBF <- function(delta, X, y, n, a) {
    .Call('bmsaplm_LogBF', PACKAGE = 'bmsaplm', delta, X, y, n, a)
}

MainSampleDelta <- function(sel_ind, fordelta, listdelta, numkn, phat) {
    .Call('bmsaplm_MainSampleDelta', PACKAGE = 'bmsaplm', sel_ind, fordelta, listdelta, numkn, phat)
}

MainSampleDeltaGlobalUpdate <- function(X, y, indset, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur, phat) {
    .Call('bmsaplm_MainSampleDeltaGlobalUpdate', PACKAGE = 'bmsaplm', X, y, indset, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur, phat)
}

MainSampleDeltaGlobalUpdateVec <- function(X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, phat) {
    .Call('bmsaplm_MainSampleDeltaGlobalUpdateVec', PACKAGE = 'bmsaplm', X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, phat)
}

MainSampleDeltaUpdate <- function(X, y, sel_ind, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur, phat) {
    .Call('bmsaplm_MainSampleDeltaUpdate', PACKAGE = 'bmsaplm', X, y, sel_ind, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur, phat)
}

MakeInd <- function(numkn) {
    .Call('bmsaplm_MakeInd', PACKAGE = 'bmsaplm', numkn)
}

#' @export
MCMCEstIteration <- function(X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, a) {
    .Call('bmsaplm_MCMCEstIteration', PACKAGE = 'bmsaplm', X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, a)
}

MCMCOneIteration <- function(X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, phat, mu, var, mu0, a) {
    .Call('bmsaplm_MCMCOneIteration', PACKAGE = 'bmsaplm', X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, phat, mu, var, mu0, a)
}

PilotSampleDelta <- function(sel_ind, fordelta, listdelta, numkn) {
    .Call('bmsaplm_PilotSampleDelta', PACKAGE = 'bmsaplm', sel_ind, fordelta, listdelta, numkn)
}

PilotSampleDeltaGlobalUpdate <- function(X, y, indset, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur) {
    .Call('bmsaplm_PilotSampleDeltaGlobalUpdate', PACKAGE = 'bmsaplm', X, y, indset, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur)
}

PilotSampleDeltaGlobalUpdateVec <- function(X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur) {
    .Call('bmsaplm_PilotSampleDeltaGlobalUpdateVec', PACKAGE = 'bmsaplm', X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur)
}

PilotSampleDeltaUpdate <- function(X, y, sel_ind, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur) {
    .Call('bmsaplm_PilotSampleDeltaUpdate', PACKAGE = 'bmsaplm', X, y, sel_ind, delta, gamma, listdelta, numkn, n, p, q, z, logbf_cur)
}

PseudoPrior <- function(delta, mu, var, numkn, mu0) {
    .Call('bmsaplm_PseudoPrior', PACKAGE = 'bmsaplm', delta, mu, var, numkn, mu0)
}

PseudoSampleDelta <- function(mu, var, numkn, mu0) {
    .Call('bmsaplm_PseudoSampleDelta', PACKAGE = 'bmsaplm', mu, var, numkn, mu0)
}

PseudoSampleDeltaVec <- function(delta, gamma, mu, var, numkn, mu0, p) {
    .Call('bmsaplm_PseudoSampleDeltaVec', PACKAGE = 'bmsaplm', delta, gamma, mu, var, numkn, mu0, p)
}

R2 <- function(X, y) {
    .Call('bmsaplm_R2', PACKAGE = 'bmsaplm', X, y)
}

SampleFixeff <- function(n, WXi, y, qv) {
    .Call('bmsaplm_SampleFixeff', PACKAGE = 'bmsaplm', n, WXi, y, qv)
}

SampleGammaLinear <- function(X, y, n, a, listdelta, gamma, p, q, z, logpost, dp) {
    .Call('bmsaplm_SampleGammaLinear', PACKAGE = 'bmsaplm', X, y, n, a, listdelta, gamma, p, q, z, logpost, dp)
}

SampleGammaLinearVec <- function(X, y, n, a, listdelta, gamma, p, q, logpost, dp) {
    .Call('bmsaplm_SampleGammaLinearVec', PACKAGE = 'bmsaplm', X, y, n, a, listdelta, gamma, p, q, logpost, dp)
}

SampleGammaNonlinear <- function(X, y, n, a, listdelta, gamma, mu, var, numkn, mu0, phat, p, q, z, logpost) {
    .Call('bmsaplm_SampleGammaNonlinear', PACKAGE = 'bmsaplm', X, y, n, a, listdelta, gamma, mu, var, numkn, mu0, phat, p, q, z, logpost)
}

SampleGammaNonlinearVec <- function(X, y, n, a, listdelta, gamma, mu, var, numkn, mu0, phat, p, q, logpost) {
    .Call('bmsaplm_SampleGammaNonlinearVec', PACKAGE = 'bmsaplm', X, y, n, a, listdelta, gamma, mu, var, numkn, mu0, phat, p, q, logpost)
}

Subset <- function(delta, X, n) {
    .Call('bmsaplm_Subset', PACKAGE = 'bmsaplm', delta, X, n)
}

#' @export
MCMCEstIterationCpp <- function(X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, a) {
    .Call('bmsaplm_MCMCEstIterationCpp', PACKAGE = 'bmsaplm', X, y, delta, gamma, listdelta, numkn, n, p, q, logbf_cur, a)
}

ZTBBPrior <- function(fordelta, numkn) {
    .Call('bmsaplm_ZTBBPrior', PACKAGE = 'bmsaplm', fordelta, numkn)
}

ZTBinPrior <- function(fordelta, numkn, phat) {
    .Call('bmsaplm_ZTBinPrior', PACKAGE = 'bmsaplm', fordelta, numkn, phat)
}

